apiVersion: v1
kind: Service
metadata:
  name: delete-note
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5003"
spec:
  type: ClusterIP
  selector:
    app: delete-note
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5003